version: "3"
services:
  api:
    image: softwareskytech/license-server:prod
    container_name: license-server
    command: ["uvicorn", "backend.main:app", "--host", "0.0.0.0", "--port", "80"]
    env_file:
      - .env
    ports:
      - "8999:80"
    networks:
      - postgres_default
